using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Base class for all AI controlled objects.
/// </summary>
[RequireComponent(typeof(Rigidbody2D), typeof(SpriteRenderer))]
public abstract class AI : MonoBehaviour
{
    [Header("Generic AI")]
    [SerializeField] private float _speed = 1f;
    private Node _currentNode;
    private List<Node> _path = new List<Node>();
    protected Rigidbody2D Rb;
    
    /// <summary>
    /// Sets <c>rb</c> to a reference of
    /// the object's <c>Rigidbody2D</c> component.
    /// </summary>
    protected virtual void Awake()
    {
        Rb = GetComponent<Rigidbody2D>();
    }
    
    /// <summary>
    /// Selects random <c>Node</c> in scene and
    /// sets it to the <c>currentNode</c>.
    /// </summary>
    protected virtual void Start()
    {
        Node[] nodes = FindObjectsOfType<Node>();
        if (nodes.Length > 0)
        {
            _currentNode = nodes[Random.Range(0, nodes.Length)];
        }
    }
    
    /// <summary>
    /// Moves the AI the <c>Nodes</c> in the scene to an end point.
    /// <para>
    /// Moves through a path generated by <c>AStarManager</c> to reach a randomly generated end <c>Node</c>.
    /// If the path has been completed or one does not currently exist, it creates a new path to a new
    /// random end <c>Node</c>.
    /// </para>
    /// <see cref="AStarManager.cs"/>
    /// </summary>
    protected void CreatePath()
    {
        if (!_currentNode) return;
        if (_path.Count > 0)
        {
            int x = 0;

            MoveTo(_path[x].transform.position);
            
            if (Vector2.Distance(transform.position, _path[x].transform.position) < 0.1f)
            {
                _currentNode = _path[x];
                _path.RemoveAt(x);
            }
        }
        else
        {
            Node[] nodes = FindObjectsOfType<Node>();
            while (_path == null || _path.Count == 0)
            {
                _path = AStarManager.s_Instance.GeneratePath(_currentNode, nodes[Random.Range(0, nodes.Length)]);
            }
        }
    }
    
    /// <summary>
    /// Sets velocity to the direction of <c>destination</c>.
    /// </summary>
    /// <param name="destination"></param>
    public void MoveTo(Vector2 destination)
    {
        Vector2 direction = (destination - new Vector2(transform.position.x, transform.position.y)).normalized;
        Rb.velocity = direction * _speed;
    }
}
